services:
  - type: web
    name: TAXI-EXPRESS
    env: php
    plan: free
    buildCommand: |
     composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
      php artisan key:generate --ansi
      php artisan migrate:fresh --force
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://taxi-express-ywvu.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3s3g5mr433s73cgjmpg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: taxi_express_odw3
      - key: DB_USERNAME
        value: taxi_express_user
      - key: DB_PASSWORD
        value: p62G3QRzb0PikUt8QDYml6ryGFny5RtM
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stack